export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS"
export const FETCH_MEMBER_DETAILS_SUCCESS = "FETCH_MEMBER_DETAILS_SUCCESS"
export const UPDATE_MEMBER_DETAILS_SUCCESS = "UPDATE_MEMBER_DETAILS_SUCCESS"
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS"

export const FETCH_SPORTS_SUCCESS = "FETCH_SPORTS_SUCCESS"

export const API_CALL_STARTED = "API_CALL_STARTED"
export const API_CALL_FAILED = "API_CALL_FAILED"
